### ISSUE TITLE
Building vicalib in Yosemite

### ISSUE THREAD

**Issue by lumark** [arpg/vicalib#20]
I notice that when building vicalib in Yosemite you may have the following linking error:

Linking CXX shared library libvicalib.dylib
ld: framework not found vecLib
collect2: error: ld returned 1 exit status
make[2]: *** [src/libvicalib.dylib] Error 1
make[1]: *** [src/CMakeFiles/vicalib.dir/all] Error 2
make: *** [all] Error 2

A solution is to change LAPACK LIB from:

/System/Library/Frameworks/vecLib.framework

To:
/Applications/Xcode.app/Contents/Developer/Platf
orms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Acc
elerate.framework/Versions/Current/Frameworks/vecLib.framework/

**Comment by gsibley** [comment]
BTW I have found this comes from our old FindCERES.cmake scripts which add
"-framework vecLib" to the link libraries.  What we need to do is add
"-framework Accelerate" instead because on Yosimte vecLib framework has
been subsumed by the Accelerate framework.  Good times with OSX.


On Fri, Mar 20, 2015 at 4:59 PM, luma <notifications@github.com> wrote:

> I notice that when building vicalib in Yosemite you may have the following
> linking error:
>
> Linking CXX shared library libvicalib.dylib
> ld: framework not found vecLib
> collect2: error: ld returned 1 exit status
> make[2]: *** [src/libvicalib.dylib] Error 1
> make[1]: *** [src/CMakeFiles/vicalib.dir/all] Error 2
> make: *** [all] Error 2
>
> A solution is to change LAPACK LIB from:
>
> /System/Library/Frameworks/vecLib.framework
>
> To:
> /Applications/Xcode.app/Contents/Developer/Platf
>
> orms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/Acc
> elerate.framework/Versions/Current/Frameworks/vecLib.framework/
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/arpg/vicalib/issues/20>.
>



-- 
Gabe Sibley, PhD

Assistant Professor
Department of Computer Science
University of Colorado, Boulder
--

**Comment by crheckman** [comment]
@gsibley this should be easily solved by just changing `FindCeresSolver.cmake` l. 202 to reference Accelerate versus vecLib. I've done it in my CRTP PR, but...

@lumark I've been building in Yosemite for awhile now and I've never run into this compile issue before. If you would like to test the change, you'll have to checkout the fix/crtp_extensions branch of calibu and rebuild, then the fix/crtp_extensions branch of vicalib and build that.

**Comment by gsibley** [comment]
This is fixed with the latest merge.
