### ISSUE TITLE
Example for calibrating IMU intrinsics

### ISSUE THREAD

**Issue by y22ma** [arpg/vicalib#25]
Hey guys,

Just wondering if it's possible to give an actual example of vicalib usage for calibration, for example, IMU intrinsics (scale, axis alignment, etc) on the README file?

**Comment by y22ma** [comment]
Furthermore, an example csv file for accel and gyro will be appreciated.

**Comment by crheckman** [comment]
We don't calibrate IMU intrinsics, only extrinsics; closing this issue.
