### ISSUE TITLE
Showing depth feed instead of IR

### ISSUE THREAD

**Issue by Algomorph** [arpg/vicalib#27]
I'm running into this issue again. Vicalib shows the depth feed instead of the IR feed.
```vicalib -grid_preset medium -cam convert:[range=ir2]//freenect2:[rgb=1,ir=1,depth=0]```
![vicalib](https://cloud.githubusercontent.com/assets/1050606/9887926/36fed6a0-5bc0-11e5-8ff5-a1e21003ac42.png)

In the meantime, HAL's sensor viewer is showing the correct depth and IR.
```./SensorViewer -cam convert:[fmt=RGB8,range=10000]//freenect2:[rgb=1,ir=1,depth=1]//```
![hal_sensorviewer](https://cloud.githubusercontent.com/assets/1050606/9887941/521cc7c6-5bc0-11e5-98f0-e95d060747c7.png)

Both are the most up-to-date versions from github. How can I get vicalib to show the IR feed & calibrate the IR camera?

**Comment by Algomorph** [comment]
With the latest freenect driver, vicalib is behaving totally berserk (showing a jumble of what seems like IR images instead of the RGB feed as well). I haven't looked deep into the issue since I'm currently not developing on the Kinect v2, but if you guys are planning to continue maintaining vicalib, it might be worth checking it.

**Comment by crheckman** [comment]
Thanks for bringing this up. We are planning on supporting vicalib for the foreseeable future and will look into this issue.

@mcguire-steve, do you run the new freenect2 driver and if so, could you hand me a data set to check this out?

**Comment by mcguire-steve** [comment]
We just fixed some bugs in Freenect2 that should solve the berserk view - that's what a RGBA image looks like if you treat it as RGB. With the following command against the latest HAL, I get solid grayscale and IR imagery suitable for calibration:
./vicalib -cam convert:[fmt=MONO8,range=depth]//freenect2:[ir=1,rgb=1,depth=0]//

Also, the latest HAL Freenect2 driver also supports choosing a pipeline at runtime amongst CPU, OpenGL, and OpenCL for the highest-performing option.
![vicalib_ok](https://cloud.githubusercontent.com/assets/5855021/11129383/356433d6-893c-11e5-9937-c1b9545d12b1.png)

**Comment by crheckman** [comment]
Thanks for getting us back to ship shape, @mcguire-steve! This should resolve the issue; if you are still having a problem @Algomorph, please feel free to reopen and we'll investigate further.
