### ISSUE TITLE
Question about testing

### ISSUE THREAD

**Issue by ayumizll** [arpg/vicalib#35]
Could you please provide another link to download the test resources. I'm trying to use your project to calibrate my camera and imu (off-line data), so the test will be a very good exemple.
But I can't download these files from link http://arpg-web.colorado.edu/~arpg/vi_sim_resources.tar.gz
I will be very grateful if you can help me.

**Comment by crheckman** [comment]
Sent via e-mail in lieu of a fully operational web server.
