### ISSUE TITLE
cmake found all depencies, but make fails

### ISSUE THREAD

**Issue by RoboBAR** [arpg/vicalib#39]
Hi,

I'm trying to install vicalib. i ran cmake and it found all of the dependencies and created the build files.
when i run 'make' i get 3 undefined references and then it fails, here are the undefined references:

undefined reference to `calibu::KannalaBrandtCamera<double>::NumParams'

undefined reference to `calibu::LinearCamera<double>::NumParams'

undefined reference to `google::base::CheckOpMessageBuilder::NewString[abi:cxx11]()

I looked all over for a fix. all of the dependencies were built with gcc/g++ 5.4.0

any help would be greatly appreciated.
-CajaYairB

**Comment by JStech** [comment]
This bug has to do with the handling of `constexpr`s in Calibu. The fix, at the moment, is to hardcode the values into vicalib. I made the attached patch a while ago--I don't know if it can be applied directly to the code now, but it should make it pretty clear how to work around this issue.

[constexpr_fix.patch.txt](https://github.com/arpg/vicalib/files/2506597/constexpr_fix.patch.txt)

**Comment by RoboBAR** [comment]
Ok thanks! that helped a lot.

This one was my fault though (for anyone else reading this!):
undefined reference to `google::base::CheckOpMessageBuilder::NewStringabi:cxx11
