### ISSUE TITLE
Could not create camera from URI.

### ISSUE THREAD

**Issue by vhanded** [arpg/vicalib#46]
After spending almost 1 whole day getting all the dependencies up, and run vicalib, I am seeing this error.

I suspect it might be issue with my camera URI, but I can't find any sample of RealSense2 URI.

Can anyone help me? I am using Realsense D410.
Firmware version: 05.11.01.100 (Just updated to 05.11.04.0, same issue)
USB: USB3.2

vhanded@vhanded-ubuntu:~/Development/lib$ `vicalib -grid_preset small -cam convert://realsense2:[size=1280x720,rgb=1,ir=0,depth=0]//`
F0527 10:59:31.723853  9777 vicalib-engine.cc:128] Could not create camera from URI: convert://realsense2:[size=1280x720,rgb=1,ir=0,depth=0]//. Reason: Couldn't resolve requests
*** Check failure stack trace: ***
    @     0x7fc3a7b7a5cd  google::LogMessage::Fail()
    @     0x7fc3a7b7c433  google::LogMessage::SendToLog()
    @     0x7fc3a7b7a15b  google::LogMessage::Flush()
    @     0x7fc3a7b7ce1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x4a43c1  visual_inertial_calibration::VicalibEngine::VicalibEngine()
    @           0x4a10f7  main
    @     0x7fc3a4df3830  __libc_start_main
    @           0x4a2309  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by JStech** [comment]
The parameters for the `realsense2` driver can be found here, https://github.com/arpg/HAL/blob/master/HAL/Camera/Drivers/RealSense2/RealSense2Factory.cpp
(Yes, digging in the code is a poor excuse for documentation. Sorry.)

Looks like you're going for something more like `realsense2:[size=1280x720,rgb=1,ir0=0,ir1=0,depth=0]//`. I don't think the `convert://` is necessary.

**Comment by vhanded** [comment]
> The parameters for the `realsense2` driver can be found here, https://github.com/arpg/HAL/blob/master/HAL/Camera/Drivers/RealSense2/RealSense2Factory.cpp
> (Yes, digging in the code is a poor excuse for documentation. Sorry.)
> 
> Looks like you're going for something more like `realsense2:[size=1280x720,rgb=1,ir0=0,ir1=0,depth=0]//`. I don't think the `convert://` is necessary.

Thanks @JStech Now I am seeing the Segmentation Fault, might because i am not compile using gcc4.6. Come back to you later. Thanks.
