### ISSUE TITLE
Pattern not found

### ISSUE THREAD

**Issue by vhanded** [arpg/vicalib#47]
When I ran vicalib with this command:

`vicalib -cam realsense2:[size=1280x720,rgb=0,ir0=1,depth=0,emitter=0]// -grid_preset small`

It shows all realsense2 that connected, 4 of them, IR0 enabled, emitter disabled. I am using D410, which don't have RGB module. 

Platform is Ubuntu 16.04, CUDA 10.

However, waving the grid in front the camera, always output the follow:
x x x x x x x x x x x x 1 x x x 
x x x x x x x x x x x 0 1 0 1 x 
x x x x x x x x x x 1 0 0 0 x x 
x x x x x x x x x 0 0 0 1 0 x x 
x x x x x x x x 1 1 0 1 0 0 x x 
x x x x x x x 0 0 0 1 0 1 x x x 
x x x x x x 1 1 1 0 1 1 x x x x 
x x x x x x 1 0 0 1 0 1 0 1 1 x 
x x x x x 1 1 1 1 1 0 0 1 0 x x 
x x x x 1 0 0 0 1 0 0 0 0 x x x 
x x x 1 1 0 0 0 1 1 0 1 x x x x 
x x 0 0 0 0 1 1 1 0 1 x x x x x 
x x x 0 0 1 0 0 1 0 x x x x x x 
x x 0 0 1 0 1 1 0 x x x x x x x 
x 0 1 1 1 1 0 1 x x x x x x x x 
x 0 0 1 x 1 1 x x x x x x x x x 
x 1 0 1 x x x x x x x x x x x x 
0 0 0 x x x x x x x x x x x x x 
x x x x x x x x x x x x x x x x 
bestscore: 2147483647, num_matches: 0, Pattern not found

The num_matches always 0, and Pattern always not found, only bestscore fluctuate.
The below is the screenshot of vicalib.
![Screenshot from 2019-05-28 21-27-43](https://user-images.githubusercontent.com/1448297/58482064-3ff7f800-8190-11e9-81e1-745f647718ac.png)

As you can see, the grid only got recognized at the center part, and not all. 

Here are a few assumption that I think is causing problem:
1. The scale of the grid is wrong. I am suppose to print small grid, when I sent for printing, they guy said this is the actual size, but it turned out quite big.

2. The grid is too big and too near to camera. But I can see clearly all the circle from the IR stream, but vicalib unable to recognize all the corners.

3. Brightness too low. 

I hope to clarify on this, before I waste money for printing again.

Thank you all so much.

**Comment by crheckman** [comment]
The target looks fine; since there are some grid dots being detected I think it's printed correctly. You could use a lot more light based on what we're seeing here. Also the target is being found in some images but not others. It looks to me that the rgb=0 and ir0=1 tags you're giving aren't being consumed properly since there are a lot of image feeds being consumed here. Could you run it with:

`cleave:[min=0,max=0]//realsense2:[size=1280x720,rgb=0,ir0=1,depth=0,emitter=0]`

And then replace min,max with 1 for the second feed?

Second, we haven't tested it with the D410 which has a rolling shutter. That could actually make it not work at all, which is why we always use the D435.

**Comment by vhanded** [comment]
Below is the (0,0) setting,
![0_0](https://user-images.githubusercontent.com/1448297/58487249-d846aa80-8199-11e9-97db-ddb20fb57039.png)

And this is (1,1) setting.
![1_1](https://user-images.githubusercontent.com/1448297/58487296-e98fb700-8199-11e9-8327-fbf8fdb1040b.png)

I have 4 cameras connected, but in my original post, I am pointing it towards camera 1 and 2. So camera 0 and camera 4 has no points. The sensors are arranged in 4 corners, 90 degree from each other.

I agree with you, that the lighting is low. I will try to install more lighting.

**Comment by crheckman** [comment]
This looks to be working as expected (poses showing up in heads up view, etc) but you will need more lighting to capture more of the target. Stepping back a few feet will help too. To estimate extrinsics across all of the cameras, the target will need to be covisible across camera pairs such that you have a fully connected network of covisibility between all camera pairs (e.g. 1-2, 2-3, 3-4 would be enough).

**Comment by vhanded** [comment]
@crheckman Thank you so much.

1. However, back to my original question, if the whole grid board is being recognized, "Pattern not found" message will be gone?

2. What if my space is really limited, and unable to step back further, using a smaller grid can work better?

3. By setting the `-save_poses` flag, vicalib will automatic save the pose, if a good camera pairs is detected?

Excuse me for a lot questions.

Thanks.

**Comment by crheckman** [comment]
The "pattern not found" message will not be gone because in certain camera views the pattern will not be found, based on your rig geometry.

A smaller target might work better given your setup, yes.

Yes on the third question too.

**Comment by vhanded** [comment]
I installed vicalib into /usr/local, and when I run, no cameras.xml is generated. Moving it out to /home works. Might be permission issue.

I also increased the brightness by increase exposure in HUD, and the detection can detect almost every dots.

Now, the pose is inaccurate, suspect is because camera not sync. Working on get the camera sync now.

**Comment by wanyp** [comment]
how do you solve this "pattern not found" problem, and how to generate a cameras.xml ? @vhanded
