### ISSUE TITLE
How to RUN V4L camera using vicalib

### ISSUE THREAD

**Issue by vishnukumarts** [arpg/vicalib#54]
I am getting the below error while one of my v4l camera.
# ./vicalib -cam V4L:

F1205 14:03:38.276158 27747 vicalib-engine.cc:128] Could not create camera from URI: V4L:. Reason: Scheme 'V4L' not registered for factory
*** Check failure stack trace: ***
    @     0x7fc6d44c90cd  google::LogMessage::Fail()
    @     0x7fc6d44caf33  google::LogMessage::SendToLog()
    @     0x7fc6d44c8c28  google::LogMessage::Flush()
    @     0x7fc6d44cb999  google::LogMessageFatal::~LogMessageFatal()
    @     0x5575df67c589  (unknown)
    @     0x5575df6799b1  (unknown)
    @     0x7fc6cfde0b97  __libc_start_main
    @     0x5575df67a85a  (unknown)
Aborted (core dumped)

I am not sure i am providing a correct syntax.

**Comment by crheckman** [comment]
V4L is not supported at the moment unless you implement it yourself in HAL. I would recommend using a different camera driver e.g. OpenCV which is widely supported.
